[build]
  publish = "my-foundation-site/public"
  command = "cd my-foundation-site && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
